import Head from "next/head";

export default function AppMeta(props: any): JSX.Element {
    return (
        <Head>
            <title>NewCal</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}
